replicaCount: 1
image:
  repository: /dvirmoyal/
  pullPolicy: IfNotPresent
  tag: ''
imagePullSecrets:
  - name: my-app-prod-registry-secret
mysql:
  host: my-app-rds.cfeiieygic3s.us-east-1.rds.amazonaws.com
