apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-my-flaskapp-prod
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-my-flaskapp
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MYSQL_HOST
              value: { { .Values.mysql.host | quote } }
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-dev-mysql-username-prod
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-dev-mysql-password-prod
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-app-dev-mysql-root-password-prod
                  key: password
            - name: MYSQL_DATABASE
              value: "worldofgame"
            - name: MYSQL_PORT
              value: "3306"