apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-my-flaskapp-prod
  ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
        nodePort: 30500
  type: NodePort